kind: Secret
apiVersion: v1
metadata: 
    name: my-secret
type: Opaque
data: 
  AWS_IAM_USER_KEY: QlVCRVdVQlZJV1M=
  AWS_IAM_USER_SECRET: VUlFRklFQmZiaXdidml1d2U=
  AWS_BUCKET_NAME: mybucket
  AWS_BUCKET_REGION: ap-south-1

